### ISSUE TITLE
BBCode marq up the windows view with Google Chrome

### ISSUE THREAD

**Issue by Galixte** [VSEphpbb/abbc3#15]
Hi,

on my live board and my test board (local), i have created a topic to explain all BBCodes (those included in this extension). The forums have this option "Enable quick reply" activated and Quickreply extension ( https://github.com/Tatiana5/QuickReply ) installed to display BBCodes on Quick reply.

When me or other user want to post a new message on this topic with Quick reply. During the posting,  when we select a part of text and apply a BBCode, the view on windows up to some previous post.

I have test and it seems those next BBCodes are the cause if there are presents in a previous post (only one of these BBCode is enough to create this situation).
```
[marq=left]Text[/marq]
[marq=right]Text[/marq]
[marq=up]Text[/marq]
[marq=down]Text[/marq]
```
This "bug" is for Google Chrome 42, no problem with Firefox 37 and Internet Explorer 11.

**Comment by VSEphpbb** [comment]
This is not an issue with this extension. If anything, it's a problem in that quick reply extension.

Even with ABBC3 disabled and removed, the issue is still there. Also, it happens with any bbcode if there is a marquee element on the page, but only when using that quick reply ext. This issue does not happen on the normal post reply page, for example, even though there are marquee elements displayed there too.

**Comment by Galixte** [comment]
Hi,

ok sorry i will report this to @Tatiana5.

**Comment by Galixte** [comment]
Hi @VSEphpbb,

do you seen the answer of @lavigor ? https://github.com/Tatiana5/QuickReply/issues/26#issuecomment-124872176
